server:
  port: 8085
  
spring:  cloud:    gateway:      routes:
      #Route Mapping      - id: product-service               #RouteIdentifiler
        uri: http://localhost:8083/       #Respective microservice URL which needs to be   mapped
        predicates:        - Path= /product/**   